export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS ='SET_INGREDIENTS';
export const MASSAGE_INGREDIENTS_FAIL = 'MASSAGE_INGREDIENTS_FAIL';


//for Orders 
export const PURCHASE_BURGER_SUCCES = 'PURCHASE_BURGER_SUCCES' ;
export const PURCHASE_BURGER_FAILER = 'PURCHASE_BURGER_FAILER' ;
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START" ;
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_OREDER_START = 'FETCH_OREDER_START' ;
export const FETCH_OREDER_SUCCESS = 'FETCH_OREDER_SUCCESS' ;
export const FETCH_OREDER_FAILER = 'FETCH_OREDER_FAILER' ;